#!/usr/sbin/nft -f

flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;

    iif lo accept
    iif != lo ip daddr 127.0.0.0/8 drop
    iif != lo ip6 daddr ::1/128 drop

    ct state established,related accept
    ct state invalid drop

    ip protocol icmp icmp type echo-request limit rate 5/second accept
    ip protocol icmp accept
    ip6 nexthdr icmpv6 accept

    tcp dport ssh meter ssh-meter { ip saddr limit rate 10/minute } accept

    log prefix "[NFT-BLOCK-IN] " flags all counter drop
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    ct state invalid drop
    log prefix "[NFT-BLOCK-FWD] " counter drop
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}

table inet raw {
  chain prerouting {
    type filter hook prerouting priority raw; policy accept;
    iif eth0 ip saddr 127.0.0.0/8 drop
    iif eth0 ip saddr 10.0.0.0/8 drop
    iif eth0 ip saddr 172.16.0.0/12 drop
    iif eth0 ip saddr 192.168.0.0/16 drop
    iif eth0 ip saddr 169.254.0.0/16 drop
    iif eth0 ip saddr 0.0.0.0/8 drop
    iif eth0 ip saddr 224.0.0.0/4 drop
    iif eth0 ip saddr 240.0.0.0/4 drop
    iif eth0 ip saddr 255.255.255.255/32 drop
  }
}
